"""feat: initalize database

Revision ID: cd4f3997fe87
Revises: 
Create Date: 2024-01-19 16:23:10.347250

"""
from alembic import op
import sqlalchemy as sa

# User-added configurations
from main.models.lti_config import create_lti_config, db

# revision identifiers, used by Alembic.
revision = 'cd4f3997fe87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lti_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iss', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('auth_login_url', sa.Text(), nullable=True),
    sa.Column('auth_token_url', sa.Text(), nullable=True),
    sa.Column('key_set_url', sa.Text(), nullable=True),
    sa.Column('private_key_file', sa.Text(), nullable=True),
    sa.Column('public_key_file', sa.Text(), nullable=True),
    sa.Column('public_jwk', sa.Text(), nullable=True),
    sa.Column('deployment_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_date', sa.Date(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance', sa.Boolean(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Manually added command
    # TODO: add configuration for this running on first time only
    lti_config = create_lti_config()
    db.session.add(lti_config)
    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('lti_config')
    # ### end Alembic commands ###
